import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = process.env.TEST_URL || 'http://127.0.0.1:3001';
const browser = await chromium.launch({ headless: true, channel: 'chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
const mockResult = { title:'Bữa cơm sau tập', summary:'Số liệu dưới đây chỉ là ước lượng trong kiểm thử.', confidence:'medium', needsClarification:false, totals:{calories:510,protein:37,carbs:58,fat:13}, items:[{name:'Cơm, gà và rau',portion:'Theo khẩu phần đã mô tả',calories:510,protein:37,carbs:58,fat:13,note:'Ước lượng / chưa kiểm chứng'}], recommendations:['Cân đối theo buổi tập.'], questions:[], assumptions:['Khối lượng là giả định kiểm thử.'], safetyFlags:[], sources:[{title:'Viện Dinh dưỡng Quốc gia',url:'https://viendinhduong.vn/',note:'Tài liệu nền.'}], dailyTarget:{calories:2500,proteinMin:91,proteinMax:130,note:'Ước lượng / chưa kiểm chứng.'}, estimated:true };
const mockQuestion = {...mockResult,title:'Cần làm rõ khẩu phần',summary:'Nếp chưa chắc về lượng bánh phở và thịt trong suất của bạn.',confidence:'low',needsClarification:true,totals:{calories:null,protein:null,carbs:null,fat:null},items:[],questions:['Tô phở cỡ nhỏ, vừa hay to? Khoảng bao nhiêu g bánh phở và thịt?']};
const mockPlan = {title:'Thực đơn hợp lịch tập',summary:'Ước lượng cho ba ngày, theo sở thích của bạn.',days:[1,2,3].map(day=>({day,meals:['Bữa sáng','Bữa trưa','Bữa tối'].map(name=>({name,foods:[{name:'Cơm gạo lứt',portion:'150 g (chín)'},{name:'Ức gà và rau',portion:'100 g gà chín, 150 g rau chín'}],note:'Khẩu phần ước lượng.'}))})),assumptions:['Lịch tập là thông tin tự khai.'],recommendations:['Thay món theo nguyên liệu sẵn có.'],safetyFlags:[],sources:[],dailyTarget:mockResult.dailyTarget,estimated:true};
async function fillProfile({age='25',weight='65',height='170',sex='male',sports=['Tập thể hình','Chạy bộ'],goal='Mục tiêu riêng',customGoal='Cải thiện sức bền cho buổi chạy dài'}={}) {
  await page.getByRole('spinbutton',{name:/^Tuổi/}).fill(age);
  await page.getByRole('spinbutton',{name:/Cân nặng/}).fill(weight);
  await page.getByRole('spinbutton',{name:/Chiều cao/}).fill(height);
  await page.getByRole('combobox',{name:/Giới tính sinh học/}).selectOption(sex);
  for(const sport of sports) await page.getByRole('checkbox',{name:sport,exact:true}).check();
  await page.getByRole('spinbutton',{name:/Thời gian tập mỗi buổi/}).fill('60');
  await page.getByRole('combobox',{name:/Mức vận động/}).selectOption('high');
  await page.getByRole('radio',{name:goal,exact:true}).check();
  if(goal==='Mục tiêu riêng') await page.getByRole('textbox',{name:/Mục tiêu riêng của bạn/}).fill(customGoal);
}
try {
  await page.goto(base); await page.getByRole('heading',{name:'Hôm nay bạn ăn gì?'}).waitFor();
  await fs.mkdir('screenshots',{recursive:true});
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click();
  assert.match(await page.getByRole('alert').innerText(),/mô tả món/);
  await page.getByRole('textbox',{name:/Món ăn & khẩu phần/}).fill('1 suất phở');
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click();
  assert.match(await page.getByRole('alert').innerText(),/đồng ý/);
  await page.locator('.consent-line input:visible').check();
  let requests=[]; await page.route('**/api/analyze',async route=>{ const data=route.request().postDataJSON(); requests.push(data); await route.fulfill({json:data.clarifications?.length ? mockResult : mockQuestion}); });
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click();
  assert.match(await page.getByRole('alert').innerText(),/tuổi/); assert.equal(requests.length,0);
  await fillProfile();
  await page.getByRole('spinbutton',{name:/Chiều cao/}).fill('');
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click();
  assert.match(await page.getByRole('alert').innerText(),/chiều cao/); assert.equal(requests.length,0);
  await page.getByRole('spinbutton',{name:/Chiều cao/}).fill('170');
  await page.getByRole('tab',{name:/Thêm ảnh món ăn/}).click();
  const png=await page.locator('.hero-art').screenshot(); await fs.writeFile('screenshots/meal-test.png',png);
  await page.locator('input[type=file]').setInputFiles({name:'bua-an.png',mimeType:'image/png',buffer:png});
  await page.locator('.upload-preview').waitFor();
  await page.screenshot({path:'screenshots/desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click();
  await page.getByRole('heading',{name:'Cho Nếp biết thêm nhé'}).waitFor();
  assert.equal(await page.locator('.macro-grid:visible').count(),0,'Do not show guessed nutrients before clarification');
  await page.getByRole('button',{name:'Gửi bổ sung & phân tích tiếp'}).click();
  assert.match(await page.getByRole('alert').innerText(),/trả lời/);
  await page.getByRole('textbox',{name:/Câu trả lời bổ sung/}).fill('Tô vừa, khoảng 150 g bánh phở chín và 80 g thịt bò.');
  await page.getByRole('button',{name:'Gửi bổ sung & phân tích tiếp'}).click();
  await page.getByRole('heading',{name:'Bữa cơm sau tập'}).waitFor();
  const followup=requests.at(-1); assert.equal(followup.meal,'1 suất phở'); assert.deepEqual(followup.profile.sports,['Tập thể hình','Chạy bộ']); assert.equal(followup.profile.goal,'custom'); assert.equal(followup.profile.sessionMinutes,60); assert.equal(followup.image,requests[0].image); assert.match(followup.clarifications[0].answer,/150 g/);
  await page.screenshot({path:'screenshots/result.png',fullPage:true});
  await page.getByRole('button',{name:'Bữa ăn cho bạn',exact:true}).click();
  assert.equal(await page.getByRole('spinbutton',{name:/^Tuổi/}).inputValue(),'','Plan inputs must be independent');
  assert.equal(await page.locator('.consent-line input:visible').isChecked(),false);
  await page.getByRole('button',{name:'Tạo thực đơn cho bạn'}).click();
  assert.match(await page.getByRole('alert').innerText(),/tuổi/);
  await fillProfile({age:'31',weight:'72',height:'178',sex:'female',sports:['Bơi lội'],goal:'Tăng cơ'});
  await page.getByRole('textbox',{name:/Sở thích ăn uống/}).fill('Món Việt, thích đồ nước và món dễ nấu.');
  await page.locator('.consent-line input:visible').check();
  let planInput; await page.route('**/api/meal-plan',async route=>{planInput=route.request().postDataJSON();await route.fulfill({json:mockPlan});});
  await page.getByRole('spinbutton',{name:/Phạm vi thực đơn/}).fill('16');
  await page.getByRole('button',{name:'Tạo thực đơn cho bạn'}).click();
  assert.match(await page.getByRole('alert').innerText(),/1 đến 15/); assert.equal(planInput,undefined);
  await page.getByRole('button',{name:'3 ngày',exact:true}).click();
  await page.getByRole('button',{name:'Tạo thực đơn cho bạn'}).click();
  await page.getByRole('heading',{name:'Thực đơn hợp lịch tập'}).waitFor();
  assert.equal(planInput.profile.age,31); assert.deepEqual(planInput.profile.sports,['Bơi lội']); assert.equal(planInput.days,3); assert.match(planInput.preferences,/Món Việt/);
  await page.getByRole('button',{name:'Ngày 3',exact:true}).click();
  await page.getByRole('heading',{name:'Ngày 3',exact:true}).waitFor();
  assert.equal(await page.locator('.plan-meal-card:visible').count(),3);
  assert.match(await page.locator('.plan-foods:visible').first().innerText(),/150 g/);
  await page.screenshot({path:'screenshots/meal-plan.png',fullPage:true});
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).first().click();
  assert.equal(await page.getByRole('spinbutton',{name:/^Tuổi/}).inputValue(),'25');
  await page.getByRole('button',{name:'Bữa ăn cho bạn',exact:true}).click();
  assert.equal(await page.getByRole('spinbutton',{name:/^Tuổi/}).inputValue(),'31','Plan state should survive navigation');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'screenshots/mobile-plan.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Plan mobile horizontal overflow');
  await page.getByRole('button',{name:'Hỏi Nếp một chút',exact:true}).click();
  await page.route('**/api/chat',route=>route.fulfill({json:{answer:'Bạn có thể cân đối món quen. Đây chỉ là tham khảo.',safetyFlags:[]}}));
  await page.getByRole('textbox',{name:'Câu hỏi cho Nếp'}).fill('Ăn gì sau tập?'); await page.getByRole('button',{name:'Gửi câu hỏi'}).click(); await page.getByText('Bạn có thể cân đối món quen.',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Góc kiến thức',exact:true}).click(); assert.equal(await page.locator('.resource-card').count(),4);
  await page.getByRole('button',{name:'Bữa ăn vừa xem',exact:true}).click(); await page.getByRole('heading',{name:'Bữa cơm sau tập'}).waitFor(); await page.getByRole('button',{name:'Xóa tất cả',exact:true}).click(); await page.getByRole('heading',{name:'Chưa có bữa ăn nào ở đây'}).waitFor();
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).first().click();
  await page.route('**/api/analyze',route=>route.fulfill({status:502,json:{error:{message:'Gateway tạm thời không khả dụng.'}}}));
  await page.getByRole('button',{name:'Phân tích bữa ăn',exact:true}).last().click(); await page.getByText('Gateway tạm thời không khả dụng.',{exact:true}).waitFor();
  await page.screenshot({path:'screenshots/mobile.png',fullPage:true}); assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.reload(); await page.getByRole('button',{name:'Bữa ăn cho bạn',exact:true}).click(); assert.equal(await page.getByRole('spinbutton',{name:/^Tuổi/}).inputValue(),''); assert.equal(await page.locator('.plan-result:visible').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS: required profiles, multiple sports, duration/custom goal, image retained across clarification, independent plan inputs and consent, 1–15 day validation, day selection, state/navigation/privacy, desktop/mobile, chat/history/sources/errors.');
} finally { await browser.close(); }
