import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, Flame, Heart, History, ImagePlus, Leaf, LoaderCircle, LockKeyhole, MessageCircle, Plus, Send, ShieldCheck, Sparkles, Sprout, Target, Trash2, Utensils, Wheat, X, Zap } from 'lucide-react';
import './styles.css';
import { emptyProfile, numericProfile, ProfileCard, validateProfile } from './profile.jsx';
import MealPlanScreen from './MealPlan.jsx';

const NAV = [{ id: 'analyze', label: 'Phân tích bữa ăn', icon: Utensils }, { id: 'plan', label: 'Bữa ăn cho bạn', icon: Leaf }, { id: 'chat', label: 'Hỏi Nếp một chút', icon: MessageCircle }, { id: 'history', label: 'Bữa ăn vừa xem', icon: History }, { id: 'resources', label: 'Góc kiến thức', icon: BookOpen }];
const EXAMPLES = [ ['🍜 Phở bò', 'Một tô phở bò: khoảng 150 g bánh phở chín, 80 g thịt bò, nước dùng và rau thơm.'], ['🍚 Cơm nhà', 'Một bát cơm trắng khoảng 150 g, 100 g ức gà áp chảo với một thìa cà phê dầu, một đĩa rau muống luộc khoảng 150 g.'], ['🥖 Bánh mì', 'Một ổ bánh mì thịt khoảng 200 g, có thịt heo, pa-tê, dưa leo và một ít sốt mayonnaise.'] ];
const SOURCES = [ { title: 'Bảng thành phần thực phẩm Việt Nam', org: 'Viện Dinh dưỡng Quốc gia · 2007', url: 'https://viendinhduong.vn/', text: 'Nguồn tham khảo về thành phần thực phẩm Việt. Nếp không coi ước lượng món ăn là dữ liệu đã tra trực tiếp từ bảng.' }, { title: 'Protein và vận động', org: 'Jäger và cộng sự · ISSN · 2017', url: 'https://doi.org/10.1186/s12970-017-0177-8', text: 'Tài liệu về protein cho người trưởng thành khỏe mạnh tập luyện. Không áp dụng máy móc cho mọi thể trạng.' }, { title: 'Ước tính năng lượng nền', org: 'Mifflin – St Jeor · 1990', url: 'https://doi.org/10.1093/ajcn/51.2.241', text: 'Phương trình ước tính chuyển hóa khi nghỉ. Đây là dự đoán, không phải phép đo nhu cầu thực tế.' }, { title: 'Nhu cầu năng lượng của con người', org: 'FAO / WHO / UNU', url: 'https://www.fao.org/4/y5686e/y5686e00.htm', text: 'Tài liệu về năng lượng và vận động. Hệ số hoạt động trong ứng dụng chỉ là giả định sơ bộ.' } ];
const value = n => n == null ? 'Chưa rõ' : new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 1 }).format(n);
async function api(path, body, signal) {
  const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal });
  let data; try { data = await response.json(); } catch { throw new Error('Máy chủ chưa phản hồi đúng định dạng. Bạn thử lại sau nhé.'); }
  if (!response.ok) throw new Error(typeof data.error === 'string' ? data.error : data.error?.message || data.message || 'Nếp chưa thể xử lý lúc này. Bạn thử lại sau nhé.');
  return data;
}

function SafetyCard() {
  return <section className="card safety-card"><div className="card-header"><ShieldCheck size={21}/><h2 className="card-heading">Hiểu đúng, ăn an tâm</h2></div><ul className="safety-list"><li>Số liệu món ăn là <strong>ước lượng, chưa kiểm chứng</strong>.</li><li>Nếp không chẩn đoán, kê đơn hay khuyên bỏ thuốc.</li><li>Có bệnh lý, đang mang thai hoặc dưới 18 tuổi? Hãy trao đổi với chuyên gia.</li></ul><p className="small-note">Đau ngực, khó thở, ngất: liên hệ cơ sở y tế; tình huống cấp cứu gọi 115.</p></section>;
}
function Result({ result, onChat }) {
  const macros = [['calories', 'Năng lượng', 'kcal', Flame, 'calorie'], ['protein', 'Chất đạm', 'g', Zap, 'protein'], ['carbs', 'Bột đường', 'g', Wheat, 'carbs'], ['fat', 'Chất béo', 'g', Heart, 'fat']];
  return <section className="card result-card" aria-label="Kết quả phân tích"><div className="result-heading"><div><span className="eyebrow"><Sparkles size={14}/> NẾP ĐÃ XEM BỮA ĂN CỦA BẠN</span><h2>{result.title || 'Bữa ăn của bạn'}</h2></div><span className="pill orange">Ước lượng</span></div><p className="muted">{result.summary}</p>
    {!!result.safetyFlags?.length && <div className="danger-banner" role="alert"><ShieldCheck size={20}/><div>{result.safetyFlags.map((t, i) => <p key={i}>{t}</p>)}</div></div>}
    <div className="macro-grid">{macros.map(([key, label, unit, Icon, cls]) => <div key={key} className={`macro-tile ${cls}`}><Icon size={19} className="macro-icon"/><span className="macro-label">{label}</span><div className="macro-value">{value(result.totals?.[key])} {result.totals?.[key] != null && <small>{unit}</small>}</div><span className="estimate-label">Ước lượng</span></div>)}</div>
    <div className="info-note"><CircleHelp size={17}/><span>Độ tin cậy {({low:'thấp', medium:'vừa', high:'tương đối cao'})[result.confidence] || 'chưa xác định'}. Khối lượng, dầu và cách chế biến có thể làm số liệu thay đổi. Các con số món ăn <strong>chưa được kiểm chứng</strong>.</span></div>
    {!!result.items?.length && <><h3 className="section-title">Trong bữa này có gì?</h3><div className="table-scroll"><table className="food-table"><thead><tr><th>Món / khẩu phần</th><th>Calo</th><th>Đạm</th><th>Bột đường</th><th>Béo</th></tr></thead><tbody>{result.items.map((item, i) => <tr key={i}><td><strong>{item.name}</strong><span>{item.portion}</span>{item.note && <span>{item.note}</span>}</td><td>{value(item.calories)}</td><td>{value(item.protein)}</td><td>{value(item.carbs)}</td><td>{value(item.fat)}</td></tr>)}</tbody></table></div><p className="small-note">Năng lượng: kcal · Các chất: g · Tất cả là ước lượng / chưa kiểm chứng.</p></>}
    {!!result.recommendations?.length && <><h3 className="section-title">Chỉnh một chút, hợp mình hơn</h3><div className="tips-list">{result.recommendations.map((tip, i) => <div className="tip-item" key={i}><span className="icon-box"><Check size={17}/></span><p>{tip}</p></div>)}</div></>}
    {!!result.questions?.length && <div className="questions-box"><strong>Cho Nếp biết thêm nhé</strong>{result.questions.map((q,i) => <p key={i}>{q}</p>)}<small>Bổ sung thông tin vào mô tả rồi phân tích lại để giảm độ bất định.</small></div>}
    {!!result.assumptions?.length && <details><summary className="section-title">Các giả định khi ước lượng</summary><ul className="safety-list">{result.assumptions.map((a,i) => <li key={i}>{a}</li>)}</ul></details>}
    {!!result.sources?.length && <details><summary className="section-title">Nguồn tham khảo & giới hạn</summary><div className="sources-list">{result.sources.map((s,i) => <div key={i}><a className="source-link" href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={14}/></a><p className="small-note">{s.note}</p></div>)}</div><p className="small-note">Các nguồn là tài liệu nền; không phải bằng chứng cho từng con số khẩu phần. Nếp không tra trực tiếp toàn bộ bảng thành phần.</p></details>}
    <button className="secondary-button" onClick={onChat}><MessageCircle size={17}/> Hỏi thêm về bữa ăn này <ArrowRight size={16}/></button>
  </section>;
}
function DailyTarget({ target }) {
  if (!target) return null;
  return <section className="card target-box"><span className="eyebrow"><Activity size={15}/> MỐC THAM KHẢO MỖI NGÀY</span><h3 className="target-value">{value(target.calories)}{target.calories != null && <small> kcal</small>}</h3>{target.proteinMin != null && <p className="target-range">Đạm: {value(target.proteinMin)}–{value(target.proteinMax)} g/ngày · ước lượng</p>}<p className="small-note">{target.note}</p><p className="small-note">Không phải đơn ăn uống. Đừng xem đây là mức bắt buộc phải đạt.</p></section>;
}

function App() {
  const [page, setPage] = useState('analyze');
  const [profile, setProfile] = useState(emptyProfile);
  const [clarifications, setClarifications] = useState([]);
  const [clarificationAnswer, setClarificationAnswer] = useState('');
  const [clarificationError, setClarificationError] = useState('');
  const [analysisInput, setAnalysisInput] = useState(null);
  const [meal, setMeal] = useState('');
  const [mode, setMode] = useState('text');
  const [image, setImage] = useState(null);
  const [imageName, setImageName] = useState('');
  const [result, setResult] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState([]);
  const [health, setHealth] = useState(null);
  const [consent, setConsent] = useState(false);
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState([]);
  const [chatBusy, setChatBusy] = useState(false);
  const [chatError, setChatError] = useState('');
  const [readingImage, setReadingImage] = useState(false);
  const inputRef = useRef(null), mealRef = useRef(null), resultRef = useRef(null), chatEnd = useRef(null), abortRef = useRef(null);
  useEffect(() => { const c = new AbortController(); fetch('/api/health', { signal: c.signal }).then(r => r.json()).then(setHealth).catch(() => {}); return () => { c.abort(); abortRef.current?.abort(); }; }, []);
  useEffect(() => { chatEnd.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }, [messages, chatBusy]);
  const switchPage = id => { setPage(id); setError(''); setChatError(''); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  async function upload(file) {
    if (!file) return;
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError('Bạn chọn ảnh JPG, PNG hoặc WebP nhé.'); return; }
    if (file.size > 8 * 1024 * 1024) { setError('Ảnh hơi lớn. Bạn chọn ảnh dưới 8 MB nhé.'); return; }
    setReadingImage(true); setError('');
    try {
      const bitmap = await createImageBitmap(file);
      const scale = Math.min(1, 1400 / Math.max(bitmap.width, bitmap.height));
      const canvas = document.createElement('canvas'); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale);
      canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
      setImage(canvas.toDataURL('image/jpeg', 0.82)); setImageName(file.name); setMode('image');
    } catch { setError('Nếp không đọc được ảnh này. Bạn thử một ảnh khác nhé.'); }
    finally { setReadingImage(false); if (inputRef.current) inputRef.current.value = ''; }
  }
  async function analyze(e) {
    e.preventDefault(); setError('');
    if (!meal.trim()) { setError('Bạn mô tả món và khẩu phần trước nhé. Ảnh chỉ bổ sung, không thay cho mô tả.'); mealRef.current?.focus(); return; }
    if (!consent) { setError('Bạn cần đồng ý gửi mô tả, hồ sơ và ảnh (nếu có) đến dịch vụ AI để phân tích.'); return; }
    const profileError = validateProfile(profile); if (profileError) { setError(profileError); return; }
    const input = { profile: numericProfile(profile), meal: meal.trim(), ...(image ? { image } : {}) };
    setAnalysisInput(input); setClarifications([]); setClarificationAnswer(''); setClarificationError('');
    setResult(null); setBusy(true); const controller = new AbortController(); abortRef.current = controller;
    try {
      const data = await api('/api/analyze', input, controller.signal);
      setResult(data); if (!data.needsClarification) setHistory(h => [{ id: crypto.randomUUID(), date: new Date().toLocaleTimeString('vi-VN', {hour:'2-digit',minute:'2-digit'}), meal: meal.trim(), result: data }, ...h].slice(0, 10));
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    } catch (err) { if (err.name !== 'AbortError') setError(err.message); }
    finally { if (abortRef.current === controller) setBusy(false); }
  }
  async function submitClarification(e) {
    e.preventDefault(); setClarificationError('');
    if (!clarificationAnswer.trim()) { setClarificationError('Bạn trả lời câu hỏi bổ sung trước nhé.'); return; }
    if (!consent) { setClarificationError('Bạn cần đồng ý gửi thông tin đến AI để phân tích tiếp.'); return; }
    if (!analysisInput || clarifications.length >= 5) { setClarificationError('Bạn bổ sung chi tiết vào mô tả món ở trên rồi phân tích lại nhé.'); return; }
    const answers = [...clarifications, { question: (result.questions?.join('\n') || 'Bạn mô tả rõ khẩu phần nhé.').slice(0, 1000), answer: clarificationAnswer.trim() }];
    setBusy(true); const controller = new AbortController(); abortRef.current = controller;
    try {
      const data = await api('/api/analyze', { ...analysisInput, clarifications: answers }, controller.signal);
      setResult(data); setClarifications(answers); setClarificationAnswer('');
      if (!data.needsClarification) setHistory(h => [{ id: crypto.randomUUID(), date: new Date().toLocaleTimeString('vi-VN', {hour:'2-digit',minute:'2-digit'}), meal: analysisInput.meal + '\nBổ sung: ' + answers.map(a=>a.answer).join('; '), result: data }, ...h].slice(0, 10));
      setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);
    } catch(err) { if(err.name!=='AbortError') setClarificationError(err.message); }
    finally { if(abortRef.current===controller) setBusy(false); }
  }
  async function sendChat(e, suggestion) {
    e?.preventDefault(); const q = (suggestion || question).trim(); if (!q || chatBusy) return;
    if (!consent) { setChatError('Bạn cần đồng ý gửi thông tin đến AI trước khi hỏi Nếp.'); return; }
    const profileError = validateProfile(profile); if (profileError) { setChatError(profileError); return; }
    setChatError(''); setQuestion(''); setMessages(m => [...m, { role: 'user', text: q }]); setChatBusy(true);
    try { const data = await api('/api/chat', { profile: numericProfile(profile), question: q, ...(result ? { mealContext: JSON.stringify({title:result.title, summary:result.summary, totals:result.totals, estimated:true}) } : {}) }); setMessages(m => [...m, { role: 'assistant', text: data.answer, safety: data.safetyFlags }]); }
    catch (err) { setChatError(err.message); setQuestion(q); }
    finally { setChatBusy(false); }
  }
  const consentControl = <label className="consent-line"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/><span>Tôi đồng ý gửi thông tin đã nhập và ảnh (nếu có) đến dịch vụ AI của Ban tổ chức để xử lý. Không cần gửi tên, bệnh án hay thông tin định danh.</span></label>;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e => {e.preventDefault(); switchPage('analyze');}}><span className="brand-mark"><Sprout size={27}/></span><span><span className="brand-name">nếp<span>.</span></span><span className="brand-subtitle">DINH DƯỠNG CÙNG BẠN</span></span></a><div className="sidebar-note">Ăn hiểu mình.<br/>Tập hết sức.</div><nav className="nav-list" aria-label="Điều hướng chính">{NAV.map(({id,label,icon:Icon}) => <button key={id} className={`nav-item ${page===id?'active':''}`} aria-current={page===id?'page':undefined} onClick={() => switchPage(id)}><Icon size={19}/><span>{label}</span>{page===id && <ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-footer"><span className="icon-box"><Leaf size={21}/></span><strong>Tốt hơn một chút,<br/>mỗi bữa ăn.</strong><p>Không cần hoàn hảo.<br/>Chỉ cần hiểu điều mình ăn.</p><span className="pill green"><Sparkles size={12}/> Đồng hành bởi AI</span></div></aside>
    <main className="main-content"><header className="topbar"><span className="mobile-brand"><Sprout size={25}/> nếp.</span><span className="breadcrumb">Không gian của bạn <ChevronRight size={14}/> <strong>{NAV.find(n=>n.id===page)?.label}</strong></span><span className="privacy-pill"><LockKeyhole size={14}/> Riêng tư trong phiên</span></header>
      {health && !health.configured && <div className="error-box" role="alert">Máy chủ chưa có GATEWAY_KEY. Bạn cần cấu hình khóa để dùng AI; Nếp không tạo kết quả giả.</div>}
      {page==='analyze' && <><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="pill green"><Sparkles size={13}/> TRỢ LÝ DINH DƯỠNG AI</span></span><h1 className="hero-title">Ăn hợp mình.<br/><span>Tập trọn sức.</span></h1><p className="hero-description">Từ tô phở sáng đến bữa cơm sau tập —<br/>cùng Nếp hiểu khẩu phần, chọn điều phù hợp.</p><div className="hero-actions"><button className="primary-button" onClick={() => mealRef.current?.focus()}>Phân tích bữa ăn <ArrowRight size={17}/></button><span className="muted"><CheckCircle2 size={15}/> Ưu tiên món Việt</span></div></div><img className="hero-art" src="/meal-bowl.svg" alt="Tô cơm nhiều màu sắc với rau xanh, cá, trứng và ngũ cốc"/><div className="floating-label"><Leaf size={15}/> Một bữa ngon, một bước khỏe</div></section>
      <div className="dashboard-grid"><div className="main-column"><form id="analyze-form" noValidate className="card" onSubmit={analyze}><div className="card-header"><div className="icon-box"><Utensils size={21}/></div><div><h2 className="card-heading">Hôm nay bạn ăn gì?</h2><p className="muted">Kể Nếp nghe, phần còn lại để Nếp giúp.</p></div><span className="pill green">Bắt đầu tại đây</span></div><div className="mode-tabs" role="tablist" aria-label="Cách nhập bữa ăn"><button type="button" role="tab" aria-selected={mode==='text'} className={`mode-tab ${mode==='text'?'active':''}`} onClick={() => setMode('text')}><Utensils size={16}/> Mô tả bữa ăn</button><button type="button" role="tab" aria-selected={mode==='image'} className={`mode-tab ${mode==='image'?'active':''}`} onClick={() => setMode('image')}><ImagePlus size={16}/> Thêm ảnh món ăn <span className="pill">Tùy chọn</span></button></div>
        <label className="field-label" htmlFor="meal">Món ăn & khẩu phần <span className="muted">· bắt buộc</span></label><textarea id="meal" ref={mealRef} className="meal-input" maxLength={4000} rows={4} value={meal} onChange={e => setMeal(e.target.value)} placeholder="Ví dụ: 1 bát cơm, 100 g ức gà áp chảo, 1 đĩa rau luộc. Mình vừa tập thể hình xong…"/><div className="input-footer"><span className="helper-text">Thêm khối lượng, dầu/sốt và cách nấu để ước lượng sát hơn.</span><span className="small-note">{meal.length}/4000</span></div><div className="example-list"><span className="small-note">Thử món quen:</span>{EXAMPLES.map(([label,text]) => <button className="example-chip" key={label} type="button" onClick={() => {setMeal(text); mealRef.current?.focus();}}>{label}<Plus size={12}/></button>)}</div>
        {(mode==='image' || image) && <div className={`upload-area ${image?'has-image':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault(); upload(e.dataTransfer.files[0]);}}>{image ? <><img className="upload-preview" src={image} alt="Ảnh món ăn bạn đã chọn"/><div className="upload-copy"><strong>{imageName}</strong><p className="small-note">Ảnh giúp nhận diện món. Khẩu phần vẫn cần bạn mô tả.</p><button type="button" className="text-button" onClick={() => inputRef.current?.click()}>Đổi ảnh</button></div><button type="button" className="upload-remove" aria-label="Xóa ảnh" onClick={()=>{setImage(null);setImageName('');}}><X size={17}/></button></> : <><ImagePlus size={26}/><div className="upload-copy"><strong>Kéo ảnh vào đây, hoặc chọn từ máy</strong><p className="small-note">JPG, PNG, WebP · tối đa 8 MB · tự thu nhỏ trước khi gửi</p></div><button type="button" className="upload-button" disabled={readingImage} onClick={()=>inputRef.current?.click()}>{readingImage?'Đang đọc…':'Chọn ảnh'}</button></>}</div>}
        <input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" aria-label="Chọn ảnh món ăn" onChange={e=>upload(e.target.files[0])}/>{consentControl}
        {error && <div className="error-box" role="alert">{error}</div>}<button className="primary-button analyze-button" disabled={busy || readingImage || health?.configured===false}>{busy?<LoaderCircle size={18} className="loading-spinner"/>:<Sparkles size={18}/>} {busy?'Nếp đang xem bữa ăn…':'Phân tích bữa ăn'} {!busy && <ArrowRight size={18}/>}</button><p className="small-note" style={{textAlign:'center'}}>Không phán xét bữa ăn. Chỉ giúp bạn hiểu rõ hơn.</p>
      </form>{busy && <div className="card loading-card" role="status"><LoaderCircle className="loading-spinner" size={28}/><h3>Đang tìm hiểu bữa ăn của bạn</h3><p className="muted">Nhận diện món · Ước lượng khẩu phần · Gợi ý theo mục tiêu</p><button className="text-button" onClick={()=>{abortRef.current?.abort();setBusy(false);}}>Dừng phân tích</button></div>}<div ref={resultRef} style={{scrollMarginTop:24}}>{result && !busy && (result.needsClarification ? <section className="card clarification-card"><span className="eyebrow"><CircleHelp size={15}/> NẾP CẦN BẠN LÀM RÕ MỘT CHÚT</span><h2 className="card-heading">Cho Nếp biết thêm nhé</h2><p className="muted">{result.summary}</p><div className="clarification-question">{result.questions?.map((q,i)=><p key={i}>{q}</p>)}</div>{clarifications.length>0 && <details><summary className="small-note">Thông tin bạn đã bổ sung</summary>{clarifications.map((a,i)=><p className="small-note" key={i}>{a.answer}</p>)}</details>}<form noValidate onSubmit={submitClarification}><label className="field-label" htmlFor="clarification-answer">Câu trả lời bổ sung <span className="required-mark">*</span></label><textarea id="clarification-answer" className="meal-input" rows={3} maxLength={1500} value={clarificationAnswer} onChange={e=>setClarificationAnswer(e.target.value)} required placeholder="Ví dụ: tô phở cỡ vừa, khoảng 150 g bánh phở chín và 80 g thịt bò; mình ăn hết tô…"/><p className="small-note">Nếp chưa đưa số liệu khi chưa đủ căn cứ. Ảnh và mô tả gốc vẫn được dùng khi phân tích tiếp.</p>{clarificationError && <div className="error-box" role="alert">{clarificationError}</div>}<div className="clarification-actions"><button className="primary-button" disabled={clarifications.length>=5}><Sparkles size={17}/> Gửi bổ sung & phân tích tiếp</button></div></form></section> : <Result result={result} onChat={()=>switchPage('chat')}/>)}</div>{!result && !busy && <div className="empty-state"><span className="icon-box"><Sprout size={23}/></span><div><strong>Bữa ăn của bạn có câu chuyện riêng.</strong><p className="muted">Nhập món ở trên để xem năng lượng, chất dinh dưỡng và gợi ý phù hợp.</p></div></div>}</div><aside className="side-column"><ProfileCard profile={profile} setProfile={setProfile} formId="analyze-form"/><DailyTarget target={result?.dailyTarget}/><SafetyCard/></aside></div></>}
      <div hidden={page!=='plan'}><MealPlanScreen api={api} configured={health?.configured} SafetyCard={SafetyCard} DailyTarget={DailyTarget}/></div>
      {page==='chat' && <><div className="page-intro"><span className="eyebrow">LẮNG NGHE & ĐỒNG HÀNH</span><h1>Hỏi Nếp một chút.</h1><p className="muted">Chuyện ăn uống và tập luyện, mình cùng tìm hiểu. Nếp sẽ nói rõ khi chưa chắc.</p></div><div className="dashboard-grid"><section className="card chat-panel"><div className="card-header"><span className="icon-box"><MessageCircle size={21}/></span><h2 className="card-heading">Góc trò chuyện cùng Nếp</h2><button className="text-button" onClick={()=>{setMessages([]);setChatError('');}} disabled={chatBusy} aria-label="Xóa cuộc trò chuyện"><Trash2 size={17}/></button></div><div className="chat-messages" aria-live="polite">{messages.length===0 && <div className="chat-bubble assistant"><strong>Chào bạn, mình là Nếp 🌱</strong><p>Bạn muốn tìm hiểu bữa ăn trước tập, cách thêm chất đạm vào món Việt hay điều chỉnh bữa vừa phân tích? Hỏi mình nhé.</p><p className="small-note">Câu trả lời AI chỉ để tham khảo, không thay tư vấn chuyên môn.</p></div>}{messages.map((m,i)=><div key={i} className={`chat-bubble ${m.role}`}><span className="small-note">{m.role==='user'?'Bạn':'Nếp'}</span><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p>{m.safety?.length>0 && <div className="danger-banner">{m.safety.join(' ')}</div>}</div>)}{chatBusy && <div className="chat-bubble assistant" role="status"><LoaderCircle size={17} className="loading-spinner"/> Nếp đang suy nghĩ…</div>}<div ref={chatEnd}/></div><div className="suggested-questions">{['Ăn gì trước buổi chạy?', 'Thêm đạm vào bữa cơm Việt thế nào?', 'Ảnh món ăn có ước lượng chính xác không?'].map(q=><button className="example-chip" key={q} disabled={chatBusy} onClick={e=>sendChat(e,q)}>{q}</button>)}</div>{consentControl}{chatError && <div className="error-box" role="alert">{chatError}</div>}<form id="chat-form" noValidate className="chat-form" onSubmit={sendChat}><label htmlFor="question" className="sr-only">Câu hỏi cho Nếp</label><input id="question" className="chat-input" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder="Bạn muốn hỏi Nếp điều gì?"/><button className="primary-button" disabled={chatBusy || !question.trim()} aria-label="Gửi câu hỏi"><Send size={18}/></button></form></section><aside className="side-column"><ProfileCard profile={profile} setProfile={setProfile} formId="chat-form"/><SafetyCard/></aside></div></>}
      {page==='history' && <><div className="page-intro"><span className="eyebrow">NHÌN LẠI ĐỂ HIỂU MÌNH</span><h1>Bữa ăn vừa xem.</h1><p className="muted">Chỉ giữ trong phiên này, tối đa 10 bữa. Tải lại trang là xóa — ảnh và hồ sơ không được lưu.</p></div><div className="history-actions"><span className="pill green">{history.length} bữa trong phiên</span><button className="text-button" disabled={!history.length} onClick={()=>{setHistory([]);setResult(null);}}><Trash2 size={16}/> Xóa tất cả</button></div>{history.length===0 ? <div className="card empty-state"><History size={32}/><div><h2>Chưa có bữa ăn nào ở đây</h2><p className="muted">Bắt đầu với một món quen, Nếp sẽ giúp bạn tìm hiểu.</p><button className="primary-button" onClick={()=>switchPage('analyze')}>Thêm bữa đầu tiên <ArrowRight size={16}/></button></div></div>:<div className="history-list">{history.map(h=><article className="card history-item" key={h.id}><span className="icon-box"><Utensils size={21}/></span><div><h2 className="card-heading">{h.result.title}</h2><p className="muted">{h.meal}</p><span className="history-meta"><Clock3 size={13}/> {h.date} · {value(h.result.totals?.calories)} kcal · ước lượng / chưa kiểm chứng</span></div><button className="secondary-button" onClick={()=>{setResult(h.result);setMeal(h.meal);setImage(null);switchPage('analyze');}}>Xem lại <ArrowRight size={15}/></button><button className="text-button" aria-label={`Xóa ${h.result.title}`} onClick={()=>setHistory(list=>list.filter(x=>x.id!==h.id))}><Trash2 size={16}/></button></article>)}</div>}</>}
      {page==='resources' && <><div className="page-intro"><span className="eyebrow">KIẾN THỨC CÓ ĐIỂM TỰA</span><h1>Hiểu nguồn. Biết giới hạn.</h1><p className="muted">Thông tin hữu ích bắt đầu từ sự minh bạch, không phải những con số trông thật chính xác.</p></div><div className="resources-grid">{SOURCES.map((s,i)=><article className="card resource-card" key={s.url}><span className="icon-box"><BookOpen size={22}/></span><span className="small-note">NGUỒN THAM KHẢO {i+1}</span><h2>{s.title}</h2><p className="small-note">{s.org}</p><p className="muted">{s.text}</p><a className="source-link" href={s.url} target="_blank" rel="noopener noreferrer">Đọc tài liệu gốc <ArrowUpRight size={16}/></a></article>)}</div><section className="card" style={{marginTop:24}}><h2 className="card-heading">Nếp dùng số liệu như thế nào?</h2><ul className="safety-list"><li>Món ăn được AI ước lượng từ mô tả và ảnh. Mọi con số khẩu phần đều mang nhãn <strong>ước lượng / chưa kiểm chứng</strong>, không giả làm số liệu từ bảng thành phần.</li><li>Thiếu khối lượng hoặc không nhận diện được món? Nếp nêu giả định, hỏi thêm, hoặc để số liệu là “Chưa rõ”.</li><li>Mốc năng lượng ngày, nếu đủ hồ sơ người trưởng thành, dùng phương trình Mifflin–St Jeor và hệ số vận động giả định. Không thay kết quả đo hay đánh giá lâm sàng.</li><li>Khuyến nghị đạm theo tài liệu ISSN dành cho người trưởng thành khỏe mạnh tập luyện. Bệnh lý, thai kỳ và trẻ vị thành niên cần chuyên gia đánh giá riêng.</li><li>Không có tài khoản, không lưu hồ sơ/ảnh vào cơ sở dữ liệu. Dịch vụ AI bên ngoài nhận thông tin để xử lý theo chính sách của họ; vì vậy đừng gửi dữ liệu nhạy cảm không cần thiết.</li></ul></section></>}
      <footer className="footer-disclaimer"><ShieldCheck size={17}/><p><strong>Nếp đồng hành, không thay chuyên gia.</strong> Chỉ hỗ trợ tham khảo, không thay bác sĩ / chuyên gia dinh dưỡng; không chẩn đoán, kê đơn hoặc khuyên tự ý bỏ thuốc. Nếu có dấu hiệu nguy hiểm, hãy liên hệ cơ sở y tế.</p><span>Được làm với sự tử tế 🌱</span></footer>
    </main></div>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
